### ISSUE TITLE
Help - having trouble mocking IO.gets

### ISSUE THREAD

**Issue by marc-costello** [jjh42/mock#27]
```
defmodule PlayerTests do
   use ExUnit.Case, async: false

   test "get input from the user" do
      Mock.with_mock IO, [gets: fn(_prompt) -> "1\n" end] do
         result = IO.gets("say something: ")
         assert result == "1\n"
      end 
   end
end
```

Not sure where I am going wrong with this. When the test is ran and ` IO.gets("say something: ")` is called it doesn't seem to have mocked the function and still prompts the console for input.

Not sure if this is related but I also can't import/require the Mock module. When I do I get a compile error:

** (CompileError) test/player_test.exs:3: module Mock is not loaded and could not be found
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (stdlib) lists.erl:1353: :lists.mapfoldl/3

**Comment by jjh42** [comment]
if you are unable to load Mock then this is probably the source of the problem.

you don't have an `import Mock` line in your example (https://github.com/jjh42/mock).

**Comment by marc-costello** [comment]
Figured it out:

```
defp deps do
    [{:mock, git: "https://github.com/jjh42/mock.git", only: :dev}]
  end
```

The `only: :dev` was preventing Mock from being compiled. Removing that or changing it to `only: :test` ensured that Mock was being built.
Thanks for your help, good job with the library
