### ISSUE TITLE
Allow interchangeable use of sigil strings and strings 

### ISSUE THREAD

**Issue by lpil** [jjh42/mock#28]
```elixir
        x = "{\"body\":\"Guidelines\\n\"}"
        assert called Foo.bar(x)
```

And

```elixir
        x = ~s({"body":"Guidelines\n"})
        assert called Foo.bar(x)
```

Are not the same. This is awkward. What's the way around this problem?

**Comment by jjh42** [comment]
@lpil I don't actively use Elixir at the moment so not an expert for solving this ... I agree its a bit awkward but is there an easy resolution without special casing it ... i.e. in general calling the sigil is not the same e.g. `~r`

**Comment by lpil** [comment]
That's interesting news. If you're not currently doing Elixir, should we be using this library?

**Comment by jjh42** [comment]
@lpil up to you. If you find it helpful, its very short so it shouldn't be too hard to maintain yourself. I've accepted a few patches from people who have updated it for changes in Elixir.

**Comment by lpil** [comment]
I'm less concerned about the code, and more about the hex package being updated. Will you accept patches and make new hex releases?

**Comment by jjh42** [comment]
@lpil in general, I've accepted patches and tried update things ... sometimes with a time lag if I'm busy.

**Comment by lpil** [comment]
Cool, ok. Thank you. :)
