### ISSUE TITLE
Assert a function was called without caring about arguments?

### ISSUE THREAD

**Issue by mrdziuban** [jjh42/mock#31]
I'm trying to write a test where I'm asserting that the `Task.async/1` function was called, but I don't care about what arguments it was called with. Here's a simple example:

```
test "calls Task.async/1" do
  with_mock Task, [async: fn(_) -> end] do
    Task.async(fn -> IO.puts("test") end)
    assert called Task.async
  end
end
```

But this test always returns `Expected truthy, got false`. Is there a way to assert that a function was called regardless of the arguments? I tried doing `assert called Task.async(_)`, but that raises a CompileError.

Alternatively, how can I specify that `Task.async` was called with an anonymous function? I've tried a few things, but haven't been able to get the test to pass. Thanks in advance!

**Comment by bartj3** [comment]
I believe you're looking for `:_`

Your example would work with:
```elixir
  test "calls Task.async/1" do
    with_mock Task, [async: fn(_) -> end] do
      Task.async(fn -> IO.puts("test") end)
      assert called Task.async :_
    end
  end
```

It's in the readme but the actual example it's referencing to is no longer there.

**Comment by mrdziuban** [comment]
Perfect, thank you @bartj3!
