### ISSUE TITLE
Execute some code when the mock is called

### ISSUE THREAD

**Issue by javflores** [jjh42/mock#37]
I have found quite handy sometimes to have the possibility to execute some code when the mock is called. One good use case is raising an exception when the mock is called.
In RhinoMocks there is something like this:
```
myStub
    .Stub(_ => _.Create(Arg<Invoice>.Is.Anything))
    .WhenCalled(_ => 
    {
        throw new Exception
    );
```
Is that possible with mock?
Thanks by the way for the nice library

**Comment by eproxus** [comment]
Yes, this is possible. As can be seen in the first example:

```elixir
defmodule MyTest do
  use ExUnit.Case, async: false

  import Mock

  test "test_name" do
    with_mock HTTPotion, [get: fn(_url) -> "<html></html>" end] do
      HTTPotion.get("http://example.com")
      # Tests that make the expected call
      assert called HTTPotion.get("http://example.com")
    end
  end
end
```

The `get` function is replaced by another function entirely, in this case an anonymous function. You can either do whatever you want in there, e.g. `[get: fn(url) -> my_code(url) end]` or just reference another function you wrote that takes the same number of arguments, e.g. `[get: &my_code/1]`.

**Comment by jjh42** [comment]
Hopefully @eproxus answer resolved your question. Thanks.
