### ISSUE TITLE
Failure when mocking exceptions

### ISSUE THREAD

**Issue by emilsoman** [jjh42/mock#42]
When mocking exceptions like this:

``` elixir
    defmodule MyModule do
      def foo, do: IO.puts "Hello world"
    end

    with_mock MyModule, [foo: fn() -> raise "ohnoz!" end] do
      try do
        MyModule.foo
      rescue
        err ->
          IO.puts "Caught error #{inspect err}"
      end
      assert called MyModule.foo
    end
```

I get the following failure:

```
     Assertion with == failed
     code: :meck.validate(MyModule) == true
     lhs:  false
     rhs:  true
```

Why do we call `:meck.validate()` after the test ? That seems to be causing the trouble.

**Comment by ksakhamuri** [comment]
I'm running into the same issue.  I think, it's a common case for a supporting library to throw exceptions and for us to handle the exceptions accordingly.  And I sure would love the ability to test for that path too.

Referring to the documentation of Meck, there seems to be a provision for "expecting" exceptions.  

> Exceptions can be anticipated by Meck (resulting in validation still passing). This is intended to be used to test code that can and should handle certain exceptions indeed does take care of them:

```
5> meck:expect(dog, meow, fun() -> meck:exception(error, not_a_cat) end).
ok
6> catch dog:meow().
{'EXIT',{not_a_cat,[{meck,exception,2},
                    {meck,exec,4},
                    {dog,meow,[]},
                    {erl_eval,do_apply,5},
                    {erl_eval,expr,5},
                    {shell,exprs,6},
                    {shell,eval_exprs,6},
                    {shell,eval_loop,3}]}}
7> meck:validate(dog).
true
```

Is this something that we can support in Mock?  I'm new to Elixir (and totally unfamiliar with Erlang), and haven't read up on macros.  Otherwise, would love to contribute back.

**Comment by emilsoman** [comment]
Btw, I stopped using mock in favor of dependency injection.

**Comment by ksakhamuri** [comment]
That's good to know @emilsoman.  Is there a different library you are using to achieve it?  Or can you point me at a place where I can understand how to do this in elixir?

Thanks,
Kalyan

**Comment by emilsoman** [comment]
Here's a quick demo of how I changed my code for DI :

```elixir
#Change this ->
defmodule MyModule do
  def get_project(url, dir) do
    Git.clone(url, dir)
  end
end


# to this ->
# See how we use a default argument.
# This means the consumers of this function don't
# have to know this change and everything works!
defmodule MyModule do
  def get_project(url, dir, scm \\ Git) do
    scm.clone(url, dir)
  end
end
```

Now you can test it like this:
```elixir
test "get_project clones a repo using scm" do
  defmodule FakeGit do
    def clone(url, dir) do
      send self, {url, dir}
    end
  end

  MyModule.get_project("fake_url", "fake_dir", FakeGit)

  receive do
    {url, dir} ->
      assert url == "fake_url"
      assert dir == "fake_dir"
  end
end
```

There are other ways to do this. Check [this blog post](http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/). But I find DI using function arguments the best way to do this, YMMV.

**Comment by ksakhamuri** [comment]
Thanks Emil for those pointers. Very helpful!
 

    On Sunday, May 1, 2016 2:46 AM, Emil Soman <notifications@github.com> wrote:
 

 Here's a quick demo of how I changed my code for DI :#Change this ->
defmodule MyModule do
  def get_project(url, dir) do
    Git.clone(url, dir)
  end
end


# to this ->
# See how we use a default argument.
# This means the consumers of this function don't
# have to know this change and everything works!
defmodule MyModule do
  def get_project(url, dir, scm \\ Git) do
    scm.clone(url, dir)
  end
endNow you can test it like this:test "get_project clones a repo using scm" do
  defmodule FakeGit do
    def clone(url, dir) do
      send self, {url, dir}
    end
  end

  MyModule.get_project("fake_url", "fake_dir", FakeGit)

  receive do
    {url, dir} ->
      assert url == "fake_url"
      assert dir == "fake_dir"
  end
endThere are other ways to do this. Check this blog post. But I find DI using function arguments the best way to do this, YMMV.—

**Comment by Olshansk** [comment]
Going to close out this issue.

Simply for the record, I did want to point out that erlang code can be executed from within elixir. For example: `meck:expect(..)` can be written as `:meck.expect(...).
