### ISSUE TITLE
Mocking a whole module by providing alternative implementation

### ISSUE THREAD

**Issue by NobbZ** [jjh42/mock#43]
I need to mock huge parts of `File`, because I have to test a function which involves heavy creating and deleting of files and folders.

To make it a little bit easier to test, I don't wan't to check if `File.rm("file")` has been called but provide some own asserts like `assertDeleted "file"` which then is independent of the rm function used (`rm`, `rm_rf` and banged versions thereof).

To keep track of file operations and such it were much easier to just implement a module which does the mocking instead of providing the list of functions as done in the example.

**Comment by jjh42** [comment]
I don't think that will work with mock currently. I think the way the interface to `:meck` works you'd have to iterate through and replace all the functions of a module. If you want to add functional to mock feel free to open a pull request.

**Comment by NobbZ** [comment]
I don't know if I'll find the time to do a PR... But if it is not possible so far, I'll mock the direct calls for now. Thank you anyway.
