### ISSUE TITLE
Syntax sugar for multiple mocks? 

### ISSUE THREAD

**Issue by douglascamata** [jjh42/mock#44]
I do not like that I need a lot of `with_mock` blocks when I need multiple mocks for a test (it happens in some projects). I would love to see a better solution for this case, but I have no idea on how to improve it. What you say?

**Comment by jjh42** [comment]
I've rarely ever needed more than one mock, maybe two. Is there a syntax you'd suggest?

**Comment by michelre** [comment]
I confirm, it would be a really nice feature. I was thinking about something like:

```elixir
with_mock [HTTPoison, File], [get:fn()->...end, :passthrough] do
 #...
end
```

In this case, we first provide all modules we need to mock and then provide the behaviour of our mocks!
Another suggestion?

**Comment by douglascamata** [comment]
@jjh42 I think of a syntax using a Map and a Keyword combination, because depending on how many mocks the syntax proposed by @michelre will become a bit hard to read. And with a Map one can easily mock many functions of the same module. Something like:


```elixir
with_mock %{HTTPoison => [get: f() -> end, post: :passtrough], File => [write: :passthrough] do
end
```

**Comment by michelre** [comment]
@douglascamata Absolutely, I agree, it is much more readable

**Comment by jjh42** [comment]
@douglascamata looks reasonable. It will probably be quite some time before I'll have a chance to do this, but I'd happily merge a (tested) patch.

**Comment by douglascamata** [comment]
@jjh42 I'm saving part of my weekend time for open-source contributions, I'll see if I can get anything done in this weekend. 

We keep backwards compatibility with the current syntax and add the new one for multiple modules/functions? I think this is the best option.

**Comment by jjh42** [comment]
Yes. I think maintain backwards compatibility is definitely the way to go.

**Comment by jjh42** [comment]
Although I think I'd change the documentation to recommend the Map syntax even for the single mock case, its quite nice.

**Comment by jjh42** [comment]
This has been added by @xieyunzi
