### ISSUE TITLE
Problems with mocking a request with timeout

### ISSUE THREAD

**Issue by gaynetdinov** [jjh42/mock#46]
Hello.

I'm mocking two get requests like this:

```
test_with_mock "my test", HTTPotion, [],
  [
    get: fn("http://my-url-one") ->
      %{body: "some get stuff", status_code: 200}
    end,
    get: fn("http://my-url-two") ->
      %{body: "{\"id\": 1}", status_code: 200}
    end
  ] do

  # ...
```

It works and everything is ok. But once I add a timeout param to the actual `http://my-url-one` request in the code:

```
HTTPotion.get("http://my-url-one", [timeout: timeout])
```

And to the mock as well:

```
get: fn("http://my-url-one", [timeout: timeout]) ->
  %{body: "some get stuff", status_code: 200}
end
```

The test gets broken with the following error: 

```
** (FunctionClauseError) no function clause matching in anonymous fn/2
```

Any clue how to properly mock a request with timeout param? 

Thanks!

**Comment by jjh42** [comment]
I think that should work. What happens if you define the mock with an generic keyword list instead of trying to match on it.

**Comment by Olshansk** [comment]
@gaynetdinov Was this ever resolved?

**Comment by gaynetdinov** [comment]
@Olshansk oh, I don't remember to be honest, but I guess it wasn't.
