### ISSUE TITLE
Mock is hard to use in test helper libraries

### ISSUE THREAD

**Issue by shosti** [jjh42/mock#50]
## Steps to reproduce:
1. Download + unzip https://files.emanuel.industries/mocktest.tar.gz (+ `mix deps.get` + `mix test`)
2. Comment out L4 of test/support/mocktest/helpers.ex (as a gist, https://gist.github.com/22b068e180a947889c08b4f399e381dc)
3. Run `mix test`
## Expected behavior

Compilation succeeds + tests pass.
## Actual behavior

Compilation fails because `with_mock` has a hidden dependency on `assert`. 

This is annoying because it's often convenient to mock external API calls (for instance) for a bunch of different tests, and a test helper library is often a good place to put that. Importing `ExUnit.Assertions` works as a workaround, but it's pretty ugly and non-obvious.

**Comment by jjh42** [comment]
So this should be fixed by having the import in the mock library itself? Would you like to submit a patch.

**Comment by Olshansk** [comment]
Removed dependency on assertion.
