### ISSUE TITLE
Question about mocking child function

### ISSUE THREAD

**Issue by echavezNS** [jjh42/mock#65]
Let's say I have something like this:

```elixir
defmodule MyModule do

   def functionA do
      :rand.uniform(10)
   end

   def functionB do
      functionA() |> add
   end

   def add(num) do
      num + 1
   end

end
```

How can I mock `functionA` but doing an assert inside the macro, something like this

```elixir
test "it should return 5 if random number is 4" do
   with_mock MyModule, [functionA: fn() -> 4 end] do
      assert MyModule.functionB() == 5
   end
end
```

I hope I can explain well my question here, I did a silly example but I need the answer in order to test a wrapper API I'm working on.

Thanks in advance.

**Comment by Olshansk** [comment]
I think what you need is the passthrough option.

Replace

`with_mock MyModule, [functionA: fn() -> 4 end] do`

with

`with_mock MyModule, [:passthrough], [functionA: fn() -> 4 end] do`

**Comment by echavezNS** [comment]
Thanks @Olshansk :)
