### ISSUE TITLE
Stronger refute statements

### ISSUE THREAD

**Issue by cheerfulstoic** [jjh42/mock#73]
Currently if I want to say that a method wasn't called I need to provide all of the arguments like:

```elixir
refute called Module.function(:green, :purple)
```

Ideally I'd like to be able to have a test which says that the method hasn't been called at all with any set of arguments.  I tried this:

```elixir
refute called Module.function(_, _)
```

But I get `unbound variable _`.

I'm still learning Elixir, so any help would be appreciated!

**Comment by spscream** [comment]
You could use :_ atom as an argument instead of_ and it will mach against any passed args

**Comment by cheerfulstoic** [comment]
That works perfectly, thanks!
