### ISSUE TITLE
with_mock and Behaviours

### ISSUE THREAD

**Issue by joebew42** [jjh42/mock#76]
Hello folks,

I started to use Elixir and since I like to practice _TDD_/_test-first-programming_ when I am at writing code I find useful to use this library to support me during the phase of `roles discovery`, which means I know I need to use a collaborator but I haven't enough information to implement it, I would like that the _discovery_ of the role is guided by tests.

In Java, an example of an implementation of the concept of roles are _interfaces_. In Elixir we have [Behaviours](https://elixir-lang.org/getting-started/typespecs-and-behaviours.html#behaviours).

I tried to create a mock of a behaviour using this library but something is wrong, or I am missing something. Maybe it is not supported yet. Here is an example of what I am trying to do:

_A role: collaborator.ex_

```
defmodule Collaborator do
  @callback save(String.t) :: {:ok, String.t}
end
```

_A test: a Client that need to use the Collaborator_

```
  test "we call a collaborator" do
    with_mock Collaborator, [save: fn(_name) -> "this is a test" end] do
      response = Client.do_something()

      assert "this is a test" == response
    end
  end
```

_A client_

```
defmodule Client do
  @collaborator Collaborator

  def do_something() do
    @collaborator.save("something")
  end
end
```

At the moment if I try to run the test I get:

```
** (ErlangError) Erlang error: {:undefined_function, {Collaborator, :save, 1}}
     code: with_mock Collaborator, [save: fn(_name) -> "this is a test" end] do
```

Maybe I am missing something, or I get this because _mock_ don't support `Behaviours` at time. Do you think that the support of `Behaviours` in _mock_ can be a good feature to add?

Thanks,
joe.

**Comment by JoanZapata** [comment]
If you use behaviors you should consider using [Mox](https://github.com/plataformatec/mox), which has the advantage of letting your tests run in parallel.

**Comment by joebew42** [comment]
Thank you @JoanZapata , it seems that Mox is exactly what I am looking for :+1: I will try it as soon as possibile, thank you!
