### ISSUE TITLE
Should assertions print what WAS called?

### ISSUE THREAD

**Issue by jasongoodwin** [jjh42/mock#78]
From a usability perspective, I find myself modifying code to printing the expected invocation because what was invoked during the test is not printed to the console.
I feel like any unexpected invocation of the mock should print, or possibly just when verifying assertions.

**Comment by Olshansk** [comment]
I feel like there can be a lot of cases where a function is mocked to limit the scope of some unit test, without the need to know how the mocked function was called.

I understand your feature request, but it is a very specific use case which is not universally true, so I don't believe it is a feature that should be part of the library. 

Let me know what you think

**Comment by jasongoodwin** [comment]
An assertion will show the expectation and the actual value. Would it not
make sense to say 'expected x but got y' or 'expected x but was not
called?' I can see your point but for expediency I would think that more
info would be strictly better. One of the reasons I'm using ExUnit for
example is for the assertion information. You can say a test failrd but to
say why and how is much more helpful when troubleshooting regressions for
instance. What changed? How is it failing now? I can't imagine that
information would ever be unhelpful.

On Nov 21, 2017 11:04 PM, "Daniel Olshansky" <notifications@github.com>
wrote:

I feel like there can be a lot of cases where a function is mocked to limit
the scope of some unit test, without the need to know how the mocked
function was called.

I understand your feature request, but it is a very specific use case which
is not universally true, so I don't believe it is a feature that should be
part of the library.

Let me know what you think

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jjh42/mock/issues/78#issuecomment-346237357>, or mute
the thread

**Comment by Olshansk** [comment]
Okay, that makes sense to me.

I probably won't have time to tend to this sometime in the near future, but you're welcome to make a PR for this feature :)

**Comment by mtrudel** [comment]
+1 to @jasongoodwin's request. Not being able to see what *was* called is very annoying in many use cases, for example when chasing down failing tests as the result of a change in call structure.
