### ISSUE TITLE
passthrough does not work 100% with Elixir

### ISSUE THREAD

**Issue by josephwilk** [jjh42/mock#8]
I've been writing my own version of mock for use with my Elixir testing framework Amrita (http://amrita.io/).

I've noticed a bug between Elixir and meck interop. Thought I would also report it here so you are aware of the problem.

I'm still trying to work out if its fixable and how.

To replicate:

```
git clone -b passthrough_bug git@github.com:josephwilk/mock.git && cd mock && MIX_ENV=test mix deps.get && mix test
```

The example failing code:

``` elixir
  defmodule Funk do
    def hip? do
      false
    end

    def hop? do
      hip?
    end

    def chicken? do
      false
    end
  end

  test "funk" do
    with_mock Funk, [:passthrough], [hip?: fn() -> true end] do
      Funk.chicken?
      assert Funk.hop?
    end
  end
```

Fail with error:

```
  1) test funk (MockTest)
     ** (UndefinedFunctionError) undefined function: MockTest.Funk_meck_original.chicken?/0
     stacktrace:
       MockTest.Funk_meck_original.chicken?()
       src/meck.erl:418: :meck.exec/5
       MockTest.Funk.chicken?()
       test/mock_test.exs:60: MockTest."test funk"/1
```

**Comment by CrowdHailer** [comment]
I have spent the morning wrestling with this apparent bug. It would be good to make a note of it in the documentation.

**Comment by jjh42** [comment]
I've add a clarification to the docs.
