### ISSUE TITLE
Mock function which comes from use have an error

### ISSUE THREAD

**Issue by OpakAlex** [jjh42/mock#82]
Hello, i have issue, when i try to mock some functions which comes from `use`, let's see an example:

```elixir
defmodule Common do
 defmacro __using__(_opts) do
   quote do
     def run(method) do 
        apply(__MODULE__, String.to_atom(method), [method])
     end 
   end
 end
end
```

test:

```elixir
defmodule CommonTest do
  use ExUnit.Case
  import Mock
  defmodule CommonWrapper
    use Common
    def test(_) do
    end
  end

test "some mock method" do
  test_fn = fn(_) -> assert :ok end
  with_mock CommonWrapper, [test: test_fn] do
     CommonWrapper.run("test")
  end
end
end
```

** (UndefinedFunctionError) function CommonWrapper.run/1 is undefined (module CommonWrapper is not available)

Any ideas?

**Comment by Olshansk** [comment]
You need to use use the passthrough option:

Replace `with_mock CommonWrapper, [test: test_fn] do` with `with_mock CommonWrapper, [:passthrough], [test: test_fn] do`.


If you search for `:passthrough` in the README, it should have all the details you need.
